baseURL = "/"
languageCode = "es"
title = "Proyecto de Ley"
theme = "PaperMod"

[params]
  mainSections = ["posts"]   # opcional: lista los posts en la home
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  [params.homeInfoParams]
    Title = "Bienvenido/a"
    Content = "Este es mi sitio personal.\n\n👉 Para ver la iniciativa y su PDF, entra en **[Iniciativa](/iniciativa/)**."
    
[menu]
  [[menu.main]]
    name = "Iniciativa"
    url = "/iniciativa/"
    weight = 1
  [[menu.main]]
    name = "Artículos"
    url = "/posts/"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true


