baseURL = "/"
languageCode = "es"
title = "Proyecto de Ley"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Iniciativa"
    url = "/iniciativa/"
    weight = 1
  [[menu.main]]
    name = "Artículos"
    url = "/posts/"
    weight = 2

[markup]
  [markup.goldmark.renderer]
    unsafe = true


